# Performance do Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Kotlin
kotlin.code.style=official
kotlin.incremental.useClasspathSnapshot=true

# KSP 2.0 (mais rápido que KSP 1)
ksp.useKSP2=false
